# TensorFlow Basics

In [1]:
import tensorflow as tf

In [2]:
# Make sure you are using 1.3 for exact sytnax matching!
print(tf.__version__)

1.3.0


## Tensors

In [7]:
hello = tf.constant('Hello')

In [8]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [9]:
world = tf.constant('World')

In [10]:
result = hello + world

In [11]:
result

<tf.Tensor 'add:0' shape=() dtype=string>

In [12]:
type(result)

tensorflow.python.framework.ops.Tensor

In [37]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [15]:
result
## b represents bytes 

b'HelloWorld'

** Computations **

In [16]:
tensor_1 = tf.constant(1)
tensor_2 = tf.constant(2)

In [12]:
type(tensor_1)


tensorflow.python.framework.ops.Tensor

In [24]:
tensor_1 + tensor_2

<tf.Tensor 'add_5:0' shape=() dtype=int32>

In [25]:
tensor_1 +tensor_2

<tf.Tensor 'add_6:0' shape=() dtype=int32>

In [26]:
with tf.Session() as sess:
    result = sess.run(tensor_1+tensor_2)

In [27]:
result

3

In [19]:
sess

In [20]:
sess.close()

## Operations

In [28]:
const = tf.constant(10)

In [39]:
fill_mat = tf.fill((4,4),10)
fill_mat

<tf.Tensor 'Fill_6:0' shape=(4, 4) dtype=int32>

In [34]:
myzeros = tf.zeros((4,4))

In [40]:
myones = tf.ones((4,4))

In [41]:
myrandn = tf.random_normal((4,4),mean=0,stddev=0.5)

In [42]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [43]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

## Interactive Session

Useful for Notebook Sessions

In [45]:
# Only run this cell once!
## USeful only for a notebook setting. 
sess = tf.InteractiveSession()

All the cells below use 'sess' created using interactive session

In [46]:
for op in my_ops:
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


[[ 0.48963782 -1.37714863  0.4731293  -0.71178788]
 [-0.19149835  0.22228064 -0.70496398  0.95563418]
 [ 0.68785912 -0.62774223 -0.29347992 -0.79056704]
 [-1.14454365 -0.39363471 -0.31863898  0.05679959]]


[[ 0.37757981  0.47546363  0.47684968  0.52051663]
 [ 0.61642265  0.09476376  0.43578196  0.99234498]
 [ 0.78333294  0.14740121  0.9062041   0.53522086]
 [ 0.34229112  0.85824072  0.95158112  0.82587373]]




## Matrix Multiplication

In [53]:
a = tf.constant([ [1,2],
                  [3,4] ])

In [54]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [55]:
b = tf.constant([[10],[100]])

In [56]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [57]:
result = tf.matmul(a,b)

In [58]:
result.eval()

array([[210],
       [430]], dtype=int32)